### PR TITLE
Use pkg-config to find OpenSSL headers, build with -std=c99 for OpenSSL >= 3.6

### LINKED ISSUE #361: Cannot compile on MacOS
# Env

MacOS Sequoia 15.7.1, Xcode-26.1. OpenSSL-3.5.4 installed by Macports  (this matters).

# Problem

Fails to compile - unable to find OpenSSL header files:
```text
$ cargo install kryoptic-tools
    Updating crates.io index
  Downloaded kryoptic-tools v1.3.1
  Downloaded 1 crate (17.1KiB) in 0.73s
  Installing kryoptic-tools v1.3.1
    Updating crates.io index
     Locking 109 packages to latest compatible versions
  Downloaded asn1_derive v0.21.3
  Downloaded asn1 v0.21.3
  Downloaded cryptoki v0.10.0
  Downloaded secrecy v0.8.0
  Downloaded cryptoki-sys v0.4.0
.  .  .  .  .
   Compiling serde_derive v1.0.228
   Compiling anstyle v1.0.13
   Compiling toml_writer v1.0.4
error: failed to run custom build command for `ossl v1.3.1`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/tmp/cargo-installZVLibP/release/build/ossl-71a3c457c521656d/build-script-build` (exit status: 101)
  --- stdout
  cargo::rustc-check-cfg=cfg(ossl_v307,ossl_v320,ossl_v350,ossl_mldsa,ossl_mlkem,ossl_slhdsa)
  cargo:rustc-link-lib=crypto
  Compile Error: "Unable to generate bindings: ClangDiagnostic(\"ossl.h:8:10: fatal error: 'openssl/core_dispatch.h' file not found\\n\")"

  --- stderr
  ossl.h:8:10: fatal error: 'openssl/core_dispatch.h' file not found
warning: build failed, waiting for other jobs to finish...
error: failed to compile `kryoptic-tools v1.3.1`, intermediate artifacts can be found at `/tmp/cargo-installZVLibP`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
$ 
```

OpenSSL headers live in `/opt/local/include/openssl/`, libraries - in `/opt/local/lib/` (symlinked from `/opt/local/libexec/openssl3/`):
```sh
$ fd core_dispatch.h /opt/local/include/openssl
/opt/local/include/openssl/core_dispatch.h
$ 
```

There needs to be a way to point `kryoptic` build process at the location of the OpenSSL binary installation.
Currently set env vars  do that, but `kryoptic` does not look at them:
```sh
$ env | grep OPENSSL
OPENSSL_LIB_DIR=/opt/local/lib
OPENSSL_INCLUDE_DIR=/opt/local/include
OPENSSL_APP=/opt/local/libexec/openssl3/bin/openssl
OPENSSL_MODULES=/opt/local/libexec/openssl3/lib/ossl-modules
OPENSSL_CFLAGS=-O3 -std=gnu18 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I/opt/local/include
OPENSSL_ROOT_DIR=/opt/local/libexec/openssl3
OPENSSL_CONF=/opt/local/etc/openssl/openssl.cnf
OPENSSL_CXXFLAGS=-std=gnu++20 -O3 -march=native -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -I/opt/local/include
OPENSSL_DIR=/opt/local/libexec/openssl3
$ 
```

### PR DESCRIPTION
**Pull request by neverpanic**
#### Description

Fixes #361.

OpenSSL will start using C99 starting with OpenSSL 3.6, so don't pass `-std=c90` for newer OpenSSL versions, see https://github.com/openssl/openssl/blob/master/NOTES-C99.md.

#### Checklist

- [ ] ~~Test suite updated with functionality tests~~
- [ ] ~~Test suite updated with negative tests~~
- [ ] ~~Rustdoc string were added or updated~~
- [ ] ~~CHANGELOG and/or other documentation added or updated~~
- [x] This is not a code change

#### Reviewer's checklist:

- [ ] Any issues marked for closing are fully addressed
- [ ] There is a test suite reasonably covering new functionality or modifications
- [ ] This feature/change has adequate documentation added
- [ ] A changelog entry is added if the change is significant
- [ ] Code conform to coding style that today cannot yet be enforced via the check style test
- [ ] Commits have short titles and sensible text
- [ ] Doc string are properly updated

### CODE REVIEW

File: ossl/build.rs
Comment (simo5) [inline ossl/build.rs]: You need to do something similar for this one, when we are building from sources.

**Review by simo5 — CHANGES_REQUESTED** [review]

File: ossl/build.rs [hunk 1]
```diff
@@ -66,7 +66,7 @@ impl bindgen::callbacks::ParseCallbacks for OsslCallbacks {
     }
 }
 
-fn ossl_bindings(args: &[&str], out_file: &Path) {
+fn ossl_bindings<T: AsRef<str>>(args: &[T], out_file: &Path) {
```
[the remark this answers is not in the document]
Comment (neverpanic) [reply ossl/build.rs]: The issue here isn't the `Vec` vs. `&[]`, it's the content type. Other call sites invoke `ossl_bindings` with borrowed strings, either because they are static strings that can be borrowed from the binary's text segment, or they are single strings that are allocated and can be referenced.

In my case, I need a vector of strings, though. Something has to own those, so I need to have a `Vec<String>` somewhere, but the function takes a collection of `&str`. Either I have to convert all other callers to use owned strings, or I need to first create a `Vec<String>` in `use_system_openssl` and then convert it to a `Vec<&str>` before passing it.

I can change it to either one of those if you want, but using the generic here allows leaving that code unchanged.
